language: rust
rust:
- stable
- beta
- nightly
os:
- linux
- osx
cache: cargo
before_cache:
- chmod -R a+r $HOME/.cargo
matrix:
  allow_failures:
  - rust: nightly
script:
- cargo build --all-features --verbose
- cargo test --all-features --verbose
env:
  global:
  - secure: XVPRd06qATbRZct/lzqqhndr+RnqMHeYCpU3xeFLC3JmURQxzbSNH0LdUCJHBrLXQEbUNoEE0Acv9xf4g6vTkjmCvxG7qzfuZspwAv1b7flobGLQoCzzc9kkd1Jiz8HgyVhcamgPmwAPl0tQBRpXYNJB9hF90nLAqLBpw6lBEhewh7BUMRyUDJQ0qEWtq3LCzHl5V7Vavz6B3tsPvvXSHTQrbbzInhGlZDxcj328bS0celauLleDkqhWZq72zicrGF3enc4ILoqd6fxspvuL6Yp4bYveinTKOhaoEL6lSAFcYzXopG1BTUs5roq+PmdBMMpL5q74nftt5MNflYup5zPGltnU3qy2oZJYs4K7Q6kzMKuaFsiKvyijjGIPTCjxqU7C3Pb91eMkJcsWfV8lWFU3iXf7GavJyhpOtlW6NWxqVGnvfSUvNStusb8PrxgpBpa5mUJ0YO6eYPpfamRAmy6teGK8vnt8GyCCum230c8CvZvG9/hT3cxgwdE5aNlI43e+4mxhl4/jSQiQReEqFtOlNVBlMcWIr7x5lvuj3WPdiyQO5vd97jrC46slXiE53JDFtBY7FZl9VQD5mHhnDGbiknl805jqBe8AJ63xcavs7Lbc9TkCCZsHsZqHt+fatEJniRig8lwkLO1UHQ/KtzAMy293Sr94KiL1zpo8bOw=
  - secure: X2mmgWqeSB8Typbbq8dYaOQzpavc9E6qk2+c4VVnh8+JWsAU9yMgkZpUn0kq+Pmwr+sM8c/5n4Mv3oUG5TZlFKxGfnpEiENQQmfuOEhTgGtaWAvd28iuXDsPLvtPyObQTiXzHDRsenWWL5kSsd+wJ/6FgiYpZOzFNEUYNItdCtK9bv1oyfJ0RXUpSz7tyI4zix6ZTQ0a0SHeEQIzeXHluemJBfcIcQuh9XXhZLyVEiZekL47rgJpzpg0gmWjGsvp1HsPDVYLA8oTNnFVCsILrZSvjFLBvM73ubih2Dqi5+XmcqsZ0qMOjnwwY4/phHD397th/MnIoFKz3PcV5JbZZjma7Ani6yKdewM4WZ5doD70x4KCs0e5gODlyVH0+PW6x7ZADJSp4hoMjYdq/YcFzXP3Apq93jyRu86APTaw9vn2g7W4SgpOJwYwrEJZ5w42bH+nGKqVSPoOKaysvhwZ9vCvm5FDW2Vgeo7f7w3krnZtofvR1kr2rJRhsXVbWq9ekkwQuOVOyxA/+dXaCCupRtQJm1ZhjwpfyjtAXzWkTvRsyoZ549fIVZOzmSVgtaI2ASMIfn8DvSL5Dzj0qSbazw96LqDQ7cIoPHRCyqX213cxg7JYPpFtO3XR9j82StCnxpBf5xYlDbqPmBzt8VLV8mCFIk37OH3EsFKrJvE5Rp0=
