language: rust
rust:
- stable
- beta
- nightly
os:
- linux
- osx
cache: cargo
before_cache:
- chmod -R a+r $HOME/.cargo
matrix:
  allow_failures:
  - rust: nightly
script:
- cargo build --all-features
- cargo test --all-features